name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: [1.23.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Build the application
        env:
          GIN_MODE=release
        run: go build -o build/app${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-build-${{ matrix.os }}
          path: |
            ./build/app${{ matrix.os == 'windows-latest' && '.exe' || '' }}
